<option value="Neurologist">Neurologist</option>
<option value="Surgeon">Surgeon</option>
<option value="Cardiologist">Cardiologist</option>
<option value="Orthopedist">Orthopedist</option>
<option value="Psychiatrist">Psychiatrist</option>
<option value="Nephrologist">Nephrologist</option>
<option value="Gynecologist">Gynecologist</option>
<option value="Allergist/Immunologist">Allergist/Immunologist</option>
<option value="Pulmonologist">Pulmonologist</option>
<option value="Emergency Physician">Emergency Physician</option>
<option value="Ophthalmologist">Ophthalmologist</option>
<option value="Oncologist">Oncologist</option>
<option value="Urologist">Urologist</option>
<option value="Otolaryngologist">Otolaryngologist</option>
<option value="Anesthesiologist">Anesthesiologist</option>
<option value="Dermatologist">Dermatologist</option>
<option value="Radiologist">Radiologist</option>
<option value="Rheumatologist">Rheumatologist</option>
<option value="Gastroenterologist">Gastroenterologist</option>
<option value="Endocrinologist">Endocrinologist</option>
<option value="Pediatrician">Pediatrician</option>
<option value="General Practitioner">General Practitioner</option>
<option value="Podiatrist">Podiatrist</option>